spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/mobile_app
spring.datasource.username=huan
spring.datasource.password=an672005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vloj0000@gmail.com
spring.mail.password=nitf mekv qhpx nvsu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=https://zn8vnhrf-8080.asse.devtunnels.ms
 
 
# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=275122292032-7ujrq4ubkofbhv1iuvm1jda3kvimh53s.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# OAuth2 success/failure URLs
app.oauth2.redirectUri=com.example.ok:/oauth2redirect

# File upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true
app.upload.dir=${user.home}/mobile-app-uploads